(()=>{
if(window.__HELLAVERSE_EVENT_MANAGER_V54__)return;
window.__HELLAVERSE_EVENT_MANAGER_V54__=1;
const STATE_KEY='hellaverse_dialogue_state_v1',VIEW_KEY='hellaverse_editor_view_v44';
const TYPES=['MILESTONE','STATE','TEMPORARY'];
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function readState(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')||{}}catch{return{}}}
function writeState(state){localStorage.setItem(STATE_KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('hellaverse:state-updated',{detail:{source:'event-manager',clearDirty:true}}));try{window.dispatchEvent(new StorageEvent('storage',{key:STATE_KEY,newValue:localStorage.getItem(STATE_KEY)}))}catch{}}
function split(v){if(Array.isArray(v))return [...new Set(v.map(String).map(x=>x.trim()).filter(Boolean))];return [...new Set(String(v||'').split(/[\n,;/|]+/).map(x=>x.trim()).filter(Boolean))]}
function slug(v){let s=String(v||'event').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');return s||`event_${Date.now()}`}
function normalizeType(v){let t=String(v||'STATE').toUpperCase();return TYPES.includes(t)?t:'STATE'}
function activeCharacter(state){return String(state.active||'')}
function suggestedId(state,name){const s=slug(name);return activeCharacter(state)==='lucifer-morningstar'?`lucifer.${s}`:s}
function definitions(state){let map=new Map();for(const src of [state.eventCatalog,state.events])for(const e of Array.isArray(src)?src:[]){let id=String(e?.id||'').trim();if(!id)continue;let prev=map.get(id)||{};map.set(id,{id,name:e.name||e.title||prev.name||id,description:e.description||e.desc||prev.description||'',type:normalizeType(e.type||prev.type),characterId:e.characterId||prev.characterId||'',namespace:e.namespace||prev.namespace||'',defined:true})}return map}
const SCENE_FIELDS=['requiredFlags','blockedFlags'];
const CHOICE_FIELDS=['requiredFlags','blockedFlags','setFlags','removeFlags'];
const GIFT_FIELDS=['requiredFlags','blockedFlags','setFlags','removeFlags','choiceASetFlags','choiceARemoveFlags','choiceBSetFlags','choiceBRemoveFlags'];
const THOUGHT_FIELDS=['requiredFlags','blockedFlags','setFlags','removeFlags'];
function addUsage(out,id,type,title,field){if(!id)return;(out.get(id)||out.set(id,[]).get(id)).push({type,title,field})}
function usageMap(state){let out=new Map();for(const s of state.dialogues||[]){for(const f of SCENE_FIELDS)for(const id of split(s[f]))addUsage(out,id,'Dialogue',s.title||s.id||'Untitled',f);for(const n of s.nodes||[])for(const c of n.choices||[])for(const f of CHOICE_FIELDS)for(const id of split(c[f]))addUsage(out,id,'Dialogue',s.title||s.id||'Untitled',`Choice · ${f}`);const meta=state.dialogueMeta?.[s.id]||{};for(const id of split(meta.completionEvents))addUsage(out,id,'Dialogue',s.title||s.id||'Untitled','Completion Event')}for(const g of state.gifts||[])for(const f of GIFT_FIELDS)for(const id of split(g[f]))addUsage(out,id,'Gift',g.name||g.id||'Untitled',f);for(const t of state.thoughts||[])for(const f of THOUGHT_FIELDS)for(const id of split(t[f]))addUsage(out,id,'Thought',(t.text||t.body||t.id||'Untitled').slice(0,60),f);return out}
function allEvents(state){let defs=definitions(state),uses=usageMap(state),ids=new Set([...defs.keys(),...Object.keys(state.flags||{}),...uses.keys()]);return [...ids].map(id=>{let d=defs.get(id);return{id,name:d?.name||id,description:d?.description||'',type:d?.type||'STATE',characterId:d?.characterId||'',namespace:d?.namespace||'',defined:!!d,orphan:!d,active:!!state.flags?.[id],usages:uses.get(id)||[]}}).sort((a,b)=>a.name.localeCompare(b.name,'ko'))}
function usageSummary(usages){let counts={Dialogue:0,Gift:0,Thought:0};for(const u of usages)counts[u.type]=(counts[u.type]||0)+1;let parts=Object.entries(counts).filter(([,n])=>n).map(([k,n])=>`${k} ${n}`);return parts.length?parts.join(' · '):'None'}
function typeHint(type){return type==='MILESTONE'?'한 번 일어나면 기록으로 남는 중요한 사건입니다.':type==='TEMPORARY'?'잠시 유지되는 상태입니다. 방문 종료 등에서 자동으로 정리될 수 있습니다.':'현재 조건에 사용되는 일반적인 사건 상태입니다.'}
function eventCard(e){return`<article class="event-manager-card ${e.orphan?'orphan':''}" data-event-card data-event-search="${esc((e.name+' '+e.id+' '+e.description+' '+e.type).toLowerCase())}" data-event-orphan="${e.orphan?'1':'0'}" data-event-active="${e.active?'1':'0'}"><div class="event-card-main"><div class="event-card-heading"><strong>${esc(e.name)}</strong>${e.orphan?'<span class="event-badge orphan">UNKNOWN / ORPHAN EVENT</span>':''}<span class="event-badge event-type">${esc(e.type)}</span><span class="event-badge status ${e.active?'active':''}">${e.active?'ACTIVE':'INACTIVE'}</span></div><small class="event-id">${esc(e.id)}</small><p>${esc(e.description||'No description')}</p><div class="event-usage"><span>Used by</span><b>${esc(usageSummary(e.usages))}</b></div></div><div class="event-card-actions">${e.active?`<button class="ghost-button" data-deactivate-event="${esc(e.id)}">DEACTIVATE</button>`:`<button class="ghost-button" data-activate-event="${esc(e.id)}">ACTIVATE</button>`}${e.defined?`<button class="text-link" data-edit-event-definition="${esc(e.id)}">EDIT EVENT</button><button class="text-link danger" data-delete-event-definition="${esc(e.id)}">DELETE EVENT DEFINITION</button>`:`<button class="text-link danger" data-remove-orphan-event="${esc(e.id)}">REMOVE COMPLETELY</button>`}${e.usages.length?`<details class="event-usage-details"><summary>SHOW USAGES</summary>${e.usages.map(u=>`<p><strong>${esc(u.type)}</strong> · ${esc(u.title)} <small>${esc(u.field)}</small></p>`).join('')}</details>`:''}</div></article>`}
function renderEventManager(){let state=readState(),events=allEvents(state);return`<section class="event-manager-page" data-event-manager-page><div class="event-manager-head"><div><p class="label">EVENT MANAGER</p><h2>EVENTS</h2><p class="muted">Event Definition과 현재 ACTIVE 상태를 관리합니다. MILESTONE은 기록, STATE는 일반 상태, TEMPORARY는 임시 상태에 사용하세요.</p></div><button class="gold-button" data-new-event>+ NEW EVENT</button></div><div class="event-manager-tools"><input type="search" data-event-manager-search placeholder="Search Event name / ID..."><div class="event-filter-row"><button class="filter-pill active" data-event-filter="all">ALL</button><button class="filter-pill" data-event-filter="active">ACTIVE</button><button class="filter-pill" data-event-filter="orphan">ORPHAN EVENTS</button></div></div><div class="event-manager-list" data-event-manager-list>${events.length?events.map(eventCard).join(''):'<p class="empty-state">아직 Event가 없습니다.</p>'}</div></section>`}
function injectStyle(){if($('#hellaverse-event-manager-v54-style'))return;let style=document.createElement('style');style.id='hellaverse-event-manager-v54-style';style.textContent='.event-badge.event-type{opacity:.72}.event-definition-modal .event-type-help{display:block;margin-top:5px;line-height:1.45}.event-definition-modal .event-id-note{display:block;margin-top:5px}';document.head.appendChild(style)}
function injectTab(){let nav=$('.editor-tabs');if(!nav||$('[data-event-section]',nav))return;let btn=document.createElement('button');btn.type='button';btn.dataset.eventSection='1';btn.textContent='EVENTS';let extras=[...nav.querySelectorAll('[data-sec]')].find(b=>b.dataset.sec==='extras');extras?nav.insertBefore(btn,extras):nav.appendChild(btn)}
function viewActive(){return sessionStorage.getItem(VIEW_KEY)==='events'}
function setView(on){on?sessionStorage.setItem(VIEW_KEY,'events'):sessionStorage.removeItem(VIEW_KEY)}
function renderView(force=false){injectStyle();injectTab();let root=$('.editor-main'),btn=$('[data-event-section]');if(!root||!btn)return;if(viewActive()){for(const b of $$('.editor-tabs button'))b.classList.remove('active');btn.classList.add('active');if(force||!$('[data-event-manager-page]',root))root.innerHTML=renderEventManager()}else btn.classList.remove('active')}
function openEvents(){setView(true);let state=readState();state.page='editor';localStorage.setItem(STATE_KEY,JSON.stringify(state));try{window.dispatchEvent(new StorageEvent('storage',{key:STATE_KEY,newValue:localStorage.getItem(STATE_KEY)}))}catch{};setTimeout(()=>renderView(true),0)}
function toast(message,detail=''){let root=$('#toastRoot')||document.body,box=document.createElement('div');box.className='toast';box.innerHTML=`<strong>${esc(message)}</strong>${detail?`<span>${esc(detail)}</span>`:''}`;root.innerHTML='';root.appendChild(box);setTimeout(()=>box.remove(),2400)}
function openForm(id=''){let state=readState(),event=allEvents(state).find(e=>e.id===id)||{id:'',name:'',description:'',type:'STATE',defined:false},root=$('#modalRoot')||document.body;root.innerHTML=`<div class="modal-backdrop"><section class="modal-card event-definition-modal"><p class="label">${id?'EDIT EVENT':'NEW EVENT'}</p><h2>${id?'Edit Event Definition':'Create Event'}</h2><input type="hidden" id="eventOriginalId" value="${esc(id)}"><label>EVENT NAME<input id="eventDefName" value="${esc(event.name||'')}"></label><label>EVENT ID<input id="eventDefId" value="${esc(event.id||'')}"><small class="event-id-note">Dialogue / Gift / Thought 조건에서 사용하는 고유 ID입니다.${activeCharacter(state)==='lucifer-morningstar'?' Lucifer 새 Event는 lucifer.* 형식을 권장합니다.':''}</small></label><label>EVENT TYPE<select id="eventDefType">${TYPES.map(t=>`<option value="${t}" ${normalizeType(event.type)===t?'selected':''}>${t}</option>`).join('')}</select><small class="event-type-help" data-event-type-help>${esc(typeHint(normalizeType(event.type)))}</small></label><label>DESCRIPTION<textarea id="eventDefDescription" rows="3">${esc(event.description||'')}</textarea></label><div class="button-row"><button class="gold-button" data-save-event-definition>${id?'SAVE EVENT':'CREATE EVENT'}</button><button class="ghost-button" data-event-modal-close>CANCEL</button></div></section></div>`}
function closeModal(){let root=$('#modalRoot');if(root)root.innerHTML=''}
function replaceTokenValue(v,oldId,newId){let arr=split(v),changed=arr.includes(oldId);if(!changed)return v;arr=arr.map(x=>x===oldId?newId:x);return Array.isArray(v)?arr:arr.join(', ')}
function renameReferences(state,oldId,newId){for(const s of state.dialogues||[]){for(const f of SCENE_FIELDS)s[f]=replaceTokenValue(s[f],oldId,newId);for(const n of s.nodes||[])for(const c of n.choices||[])for(const f of CHOICE_FIELDS)c[f]=replaceTokenValue(c[f],oldId,newId);let meta=state.dialogueMeta?.[s.id];if(meta?.completionEvents)meta.completionEvents=split(meta.completionEvents).map(x=>x===oldId?newId:x)}for(const g of state.gifts||[])for(const f of GIFT_FIELDS)g[f]=replaceTokenValue(g[f],oldId,newId);for(const t of state.thoughts||[])for(const f of THOUGHT_FIELDS)t[f]=replaceTokenValue(t[f],oldId,newId);if(state.flags?.[oldId]){state.flags[newId]=true;delete state.flags[oldId]}}
function upsertDefinition(list,id,name,description,type,oldId='',extras={}){list=Array.isArray(list)?list:[];let i=list.findIndex(e=>e?.id===oldId||e?.id===id),next={...(i>=0?list[i]:{}),...extras,id,name,description,type:normalizeType(type)};if(i>=0)list[i]=next;else list.push(next);return list}
function saveDefinition(){let state=readState(),oldId=String($('#eventOriginalId')?.value||'').trim(),name=String($('#eventDefName')?.value||'').trim(),id=String($('#eventDefId')?.value||'').trim()||suggestedId(state,name),description=String($('#eventDefDescription')?.value||'').trim(),type=normalizeType($('#eventDefType')?.value);if(!name){toast('EVENT NAME REQUIRED');return}if(!id){toast('EVENT ID REQUIRED');return}let existing=allEvents(state).find(e=>e.id===id);if(existing&&id!==oldId){toast('EVENT ID ALREADY EXISTS');return}if(oldId&&id!==oldId){let uses=usageMap(state).get(oldId)||[];if(!confirm(`Change Event ID?\n\n${oldId} → ${id}\n\n${uses.length?`This Event is used in ${uses.length} place(s). References will be updated automatically.`:'Current state and definition will be moved to the new ID.'}`))return;renameReferences(state,oldId,id);for(const key of ['events','eventCatalog'])if(Array.isArray(state[key]))state[key]=state[key].filter(e=>e?.id!==oldId)}const extras=activeCharacter(state)==='lucifer-morningstar'?{characterId:'lucifer-morningstar',namespace:'lucifer'}:{};state.events=upsertDefinition(state.events,id,name,description,type,id,extras);if(Array.isArray(state.eventCatalog)&&state.eventCatalog.some(e=>e?.id===id))state.eventCatalog=upsertDefinition(state.eventCatalog,id,name,description,type,id,extras);writeState(state);closeModal();setTimeout(()=>renderView(true),0);toast(oldId?'EVENT UPDATED':'EVENT CREATED')}
function setStatus(id,active){let state=readState();state.flags=state.flags||{};active?state.flags[id]=true:delete state.flags[id];writeState(state);setTimeout(()=>renderView(true),0);toast(active?'EVENT ACTIVATED':'EVENT DEACTIVATED')}
function removeDefinition(id,orphan=false){let state=readState(),event=allEvents(state).find(e=>e.id===id);if(!event)return;let uses=event.usages||[];if(uses.length){toast('EVENT IS IN USE',usageSummary(uses));return}let message=orphan?`Remove "${event.name}" completely?\n\nEvent definition and current active state will be removed.`:`Delete Event Definition "${event.name}"?\n\nThe definition and current active state will be removed. Memories and conversation history are not deleted.`;if(!confirm(message))return;for(const key of ['events','eventCatalog'])if(Array.isArray(state[key]))state[key]=state[key].filter(e=>e?.id!==id);if(state.flags)delete state.flags[id];writeState(state);setTimeout(()=>renderView(true),0);toast(orphan?'EVENT REMOVED':'EVENT DELETED')}
function applySearch(){let q=String($('[data-event-manager-search]')?.value||'').toLowerCase().trim(),active=$('[data-event-filter].active')?.dataset.eventFilter||'all';for(const card of $$('[data-event-card]')){let match=!q||String(card.dataset.eventSearch||'').includes(q),filter=active==='all'||(active==='active'&&card.dataset.eventActive==='1')||(active==='orphan'&&card.dataset.eventOrphan==='1');card.hidden=!(match&&filter)}}
function handleClick(e){let t=e.target;if(!(t instanceof Element))return;if(t.closest('[data-manage-events]')){e.preventDefault();e.stopImmediatePropagation();openEvents();return}if(t.closest('[data-event-section]')){e.preventDefault();e.stopImmediatePropagation();setView(true);renderView(true);return}if(t.closest('[data-sec]')){setView(false);return}if(t.closest('[data-page]')&&!t.closest('[data-page="editor"]'))setView(false);if(t.closest('[data-new-event]')){openForm();return}let edit=t.closest('[data-edit-event-definition]')?.dataset.editEventDefinition;if(edit){openForm(edit);return}let act=t.closest('[data-activate-event]')?.dataset.activateEvent;if(act){setStatus(act,true);return}let de=t.closest('[data-deactivate-event]')?.dataset.deactivateEvent;if(de){setStatus(de,false);return}let del=t.closest('[data-delete-event-definition]')?.dataset.deleteEventDefinition;if(del){removeDefinition(del,false);return}let orphan=t.closest('[data-remove-orphan-event]')?.dataset.removeOrphanEvent;if(orphan){removeDefinition(orphan,true);return}if(t.closest('[data-save-event-definition]')){saveDefinition();return}if(t.closest('[data-event-modal-close]')){closeModal();return}let filter=t.closest('[data-event-filter]')?.dataset.eventFilter;if(filter){$$('[data-event-filter]').forEach(b=>b.classList.toggle('active',b===t.closest('[data-event-filter]')));applySearch();return}}
function handleInput(e){let t=e.target;if(!(t instanceof Element))return;if(t.matches('[data-event-manager-search]'))applySearch();if(t.id==='eventDefName'&&!String($('#eventOriginalId')?.value||'')){let id=$('#eventDefId');if(id&&!id.dataset.touched)id.value=suggestedId(readState(),t.value)}if(t.id==='eventDefId')t.dataset.touched='1';if(t.closest('[data-event-manager-page]'))e.stopImmediatePropagation()}
function handleChange(e){let t=e.target;if(!(t instanceof Element))return;if(t.id==='eventDefType'){let h=$('[data-event-type-help]');if(h)h.textContent=typeHint(normalizeType(t.value))}}
function observe(){let app=$('#app');if(app&&!app.dataset.eventObserverV54){app.dataset.eventObserverV54='1';new MutationObserver(()=>queueMicrotask(()=>renderView(false))).observe(app,{childList:true,subtree:true})}}
document.addEventListener('click',handleClick,true);document.addEventListener('input',handleInput,true);document.addEventListener('change',handleChange,true);window.addEventListener('hellaverse:state-updated',()=>{if(viewActive())setTimeout(()=>renderView(true),0)});document.addEventListener('DOMContentLoaded',()=>{observe();renderView(false)});window.addEventListener('load',()=>{observe();renderView(false)});setTimeout(()=>{observe();renderView(false)},120);
})();
