(()=>{
if(window.__HELLAVERSE_RELATIONSHIP_EDITOR_V44__)return;
window.__HELLAVERSE_RELATIONSHIP_EDITOR_V44__=1;
const STATE_KEY='hellaverse_dialogue_state_v1';
const MOODS=[{id:'GOOD',label:'행복'},{id:'NORMAL',label:'보통'},{id:'TIRED',label:'피곤함'},{id:'ANNOYED',label:'화남 / 짜증'},{id:'SAD',label:'슬픔'},{id:'EXCITED',label:'신남'}];
const DEFAULT_STAGES=[{min:0,max:9,name:'STRANGER',description:'아직 거의 모르는 관계'},{min:10,max:19,name:'DISTANT',description:'조금 익숙해졌지만 아직 거리가 있는 관계'},{min:20,max:29,name:'ACQUAINTANCE',description:'서로 어느 정도 알고 있는 관계'},{min:30,max:39,name:'FAMILIAR',description:'상대에게 제법 익숙해진 관계'},{min:40,max:49,name:'COMFORTABLE',description:'함께 있어도 어색하지 않은 관계'},{min:50,max:59,name:'FRIENDLY',description:'상대에게 호의적인 관계'},{min:60,max:69,name:'CLOSE',description:'가까운 관계'},{min:70,max:79,name:'TRUSTED',description:'서로 신뢰하기 시작한 관계'},{min:80,max:89,name:'BONDED',description:'깊은 유대가 생긴 관계'},{min:90,max:99,name:'DEVOTED',description:'매우 특별하고 깊은 관계'},{min:100,max:100,name:'SPECIAL',description:'최고 단계의 특별한 관계'}];
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clamp=v=>Math.max(0,Math.min(100,Number(v||0)));
function readState(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')||{}}catch{return{}}}
function emitStorage(){try{window.dispatchEvent(new StorageEvent('storage',{key:STATE_KEY,newValue:localStorage.getItem(STATE_KEY)}))}catch{window.dispatchEvent(new Event('storage'))}}
function writeState(state){localStorage.setItem(STATE_KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('hellaverse:state-updated',{detail:{source:'relationship-editor',clearDirty:true}}))}
function parseStageLine(line){let m=String(line||'').match(/^\s*(\d+)\s*[-–~]\s*(\d+)\s*[:=]?\s*(.+?)\s*$/);return m?{min:Number(m[1]),max:Number(m[2]),name:String(m[3]).trim(),description:''}:null}
function normalizeStageRows(a={}){if(Array.isArray(a.stageTable)&&a.stageTable.length){let rows=a.stageTable.map(r=>({min:Number(r.min),max:Number(r.max),name:String(r.name||'').trim(),description:String(r.description||'')})).filter(r=>Number.isFinite(r.min)&&Number.isFinite(r.max)&&r.name);if(rows.length)return rows}if(Array.isArray(a.stages)&&a.stages.length&&typeof a.stages[0]==='object'){let rows=a.stages.map(r=>({min:Number(r.min),max:Number(r.max),name:String(r.name||'').trim(),description:String(r.description||'')})).filter(r=>Number.isFinite(r.min)&&Number.isFinite(r.max)&&r.name);if(rows.length)return rows}let raw=Array.isArray(a.stages)?a.stages:String(a.stages||'').split('\n'),rows=raw.map(parseStageLine).filter(Boolean);return rows.length?rows:DEFAULT_STAGES.map(r=>({...r}))}
function serializeStages(rows){return rows.map(r=>`${r.min}-${r.max}: ${r.name}`)}
function stageForHeart(rows,heart){return rows.find(r=>heart>=Number(r.min)&&heart<=Number(r.max))||null}
function moodLabel(id){return MOODS.find(m=>m.id===String(id||'NORMAL').toUpperCase())?.label||'보통'}
function currentMood(state,cid){let v=String(state.moods?.[cid]||'NORMAL').toUpperCase();return MOODS.some(m=>m.id===v)?v:'NORMAL'}
function ensureDefaultStages(){let state=readState(),changed=false;if(!Array.isArray(state.characters))return false;state.affection=state.affection||{};for(const c of state.characters){let a=state.affection[c.id]||{},has=(Array.isArray(a.stageTable)&&a.stageTable.length)||((Array.isArray(a.stages)&&a.stages.length)||String(a.stages||'').trim());if(!has){state.affection[c.id]={...a,value:clamp(a.value),stageTable:DEFAULT_STAGES.map(r=>({...r})),stages:serializeStages(DEFAULT_STAGES)};changed=true}}if(changed){writeState(state);emitStorage()}return changed}
function stageRow(row){return`<div class="relationship-stage-row" data-stage-row><label><span>Min Heart</span><input data-stage-min type="number" min="0" max="100" value="${esc(row.min)}"></label><label><span>Max Heart</span><input data-stage-max type="number" min="0" max="100" value="${esc(row.max)}"></label><label><span>Stage Name</span><input data-stage-name value="${esc(row.name)}"></label><label class="relationship-stage-description"><span>Description</span><input data-stage-description value="${esc(row.description||'')}"></label><div class="relationship-stage-actions"><button type="button" class="ghost-button compact" data-stage-up>↑</button><button type="button" class="ghost-button compact" data-stage-down>↓</button><button type="button" class="text-link danger" data-stage-delete>DELETE</button></div></div>`}
function relationshipMarkup(state,cid){let a=state.affection?.[cid]||{},heart=clamp(a.value),rows=normalizeStageRows(a),mood=currentMood(state,cid),current=stageForHeart(rows,heart),name=state.characters?.find(c=>c.id===cid)?.name||'Character';return`<article class="editor-card relationship-editor-v44" data-relationship-v44 data-character-name="${esc(name)}"><p class="label">RELATIONSHIP</p><section class="relationship-current"><span class="relationship-current-label">CURRENT RELATIONSHIP</span><strong>♥ <b data-current-heart>${heart}</b></strong><h2 data-current-stage>${esc(current?.name||'NO STAGE')}</h2><p data-current-description>${esc(current?.description||'현재 Heart를 포함하는 Stage가 없습니다.')}</p></section><section class="relationship-basic-section"><h3>AFFECTION</h3><label class="relationship-heart-field"><span>Heart</span><input id="rAffV44" type="number" min="0" max="100" value="${heart}"></label><button type="button" class="ghost-button danger relationship-reset-affection" data-reset-affection>RESET AFFECTION</button></section><section class="relationship-basic-section"><h3>MOOD</h3><p class="relationship-help">현재 캐릭터의 감정 상태입니다. 일부 Dialogue, Choice, Thought는 특정 Mood에서만 나타납니다.</p><label class="relationship-mood-field"><span>Current Mood</span><select id="rMoodV44">${MOODS.map(m=>`<option value="${m.id}" ${mood===m.id?'selected':''}>${m.id} — ${m.label}</option>`).join('')}</select></label><p class="relationship-mood-note" data-mood-note><strong>${esc(mood)} — ${esc(moodLabel(mood))}</strong></p></section><section class="relationship-basic-section relationship-stages-section"><div class="relationship-section-head"><span><h3>RELATIONSHIP STAGES</h3><p class="relationship-help">Heart 범위에 따라 현재 Relationship Stage가 결정됩니다. 각 Heart 값은 하나의 Stage에만 포함될 수 있습니다.</p></span><button type="button" class="ghost-button" data-stage-add>+ ADD STAGE</button></div><div class="relationship-stage-head" aria-hidden="true"><span>Min Heart</span><span>Max Heart</span><span>Stage Name</span><span>Description</span><span></span></div><div class="relationship-stage-table" data-stage-table>${rows.map(stageRow).join('')}</div><p class="relationship-validation is-hidden" data-stage-validation></p><button type="button" class="text-link" data-restore-default-stages>RESTORE DEFAULT STAGES</button></section><div class="button-row"><button type="button" class="gold-button" data-save-rel-v44>SAVE RELATIONSHIP</button></div></article>`}
function readRows(){return $$('[data-stage-row]').map(row=>({min:Number($('[data-stage-min]',row)?.value),max:Number($('[data-stage-max]',row)?.value),name:String($('[data-stage-name]',row)?.value||'').trim(),description:String($('[data-stage-description]',row)?.value||'').trim()}))}
function validateRows(rows){if(!rows.length)return'최소 한 개의 Relationship Stage가 필요합니다.';for(let i=0;i<rows.length;i++){let r=rows[i];if(!Number.isFinite(r.min)||!Number.isFinite(r.max))return`${i+1}번째 Stage의 Heart 범위를 확인해주세요.`;if(r.min<0||r.max>100)return`${i+1}번째 Stage는 0~100 범위 안에서 설정해주세요.`;if(r.min>r.max)return`${i+1}번째 Stage의 Min Heart가 Max Heart보다 큽니다.`;if(!r.name)return`${i+1}번째 Stage Name을 입력해주세요.`}let s=rows.map(r=>({...r})).sort((a,b)=>a.min-b.min||a.max-b.max);for(let i=1;i<s.length;i++)if(s[i].min<=s[i-1].max)return`Stage 범위가 겹칩니다: ${s[i-1].name} ${s[i-1].min}-${s[i-1].max} / ${s[i].name} ${s[i].min}-${s[i].max}`;return''}
function updatePreview(){let heart=clamp($('#rAffV44')?.value||0),rows=readRows(),current=stageForHeart(rows,heart),error=validateRows(rows),box=$('[data-stage-validation]');if($('[data-current-heart]'))$('[data-current-heart]').textContent=heart;if($('[data-current-stage]'))$('[data-current-stage]').textContent=current?.name||'NO STAGE';if($('[data-current-description]'))$('[data-current-description]').textContent=current?.description||'현재 Heart를 포함하는 Stage가 없습니다.';if(box){box.textContent=error;box.classList.toggle('is-hidden',!error)}}
function toast(message,detail=''){let root=$('#toastRoot')||document.body,box=document.createElement('div');box.className='toast';box.innerHTML=`<strong>${esc(message)}</strong>${detail?`<span>${esc(detail)}</span>`:''}`;root.innerHTML='';root.appendChild(box);setTimeout(()=>box.remove(),2400)}
function patchRelationship(){let old=$('#rStages')?.closest('.editor-card');if(!old||old.dataset.relationshipReplaced)return;let state=readState(),cid=state.active;if(!cid)return;let a=state.affection?.[cid]||{};if(!(Array.isArray(a.stageTable)&&a.stageTable.length)&&!(Array.isArray(a.stages)&&a.stages.length)&&!String(a.stages||'').trim()){state.affection=state.affection||{};state.affection[cid]={...a,value:clamp(a.value),stageTable:DEFAULT_STAGES.map(r=>({...r})),stages:serializeStages(DEFAULT_STAGES)};writeState(state)}old.dataset.relationshipReplaced='1';old.outerHTML=relationshipMarkup(state,cid)}
function saveRelationship(){let state=readState(),cid=state.active;if(!cid)return;let rows=readRows(),error=validateRows(rows),validation=$('[data-stage-validation]');if(error){if(validation){validation.textContent=error;validation.classList.remove('is-hidden')}toast('SAVE FAILED',error);return}let heart=clamp($('#rAffV44')?.value||0),mood=String($('#rMoodV44')?.value||'NORMAL').toUpperCase(),old=state.affection?.[cid]||{};state.affection=state.affection||{};if(!Object.prototype.hasOwnProperty.call(old,'legacyStages')&&old.stages)old.legacyStages=JSON.parse(JSON.stringify(old.stages));state.affection[cid]={...old,value:heart,stageTable:rows.map(r=>({...r})),stages:serializeStages(rows)};state.moods=state.moods||{};state.moods[cid]=MOODS.some(m=>m.id===mood)?mood:'NORMAL';try{writeState(state)}catch(e){console.error(e);toast('SAVE FAILED');return}let saved=readState(),sa=saved.affection?.[cid],ok=Number(sa?.value)===heart&&String(saved.moods?.[cid])===state.moods[cid]&&JSON.stringify(sa?.stageTable||[])===JSON.stringify(state.affection[cid].stageTable);if(!ok){toast('SAVE FAILED');return}updatePreview();emitStorage();toast('RELATIONSHIP SAVED')}
function suggestedGap(){let rows=readRows().filter(r=>Number.isFinite(r.min)&&Number.isFinite(r.max)).sort((a,b)=>a.min-b.min);let cursor=0;for(const r of rows){if(cursor<r.min)return{min:cursor,max:r.min-1};cursor=Math.max(cursor,r.max+1);if(cursor>100)break}return cursor<=100?{min:cursor,max:100}:null}
function moveStage(row,dir){let p=row?.parentElement;if(!p)return;if(dir<0&&row.previousElementSibling)p.insertBefore(row,row.previousElementSibling);if(dir>0&&row.nextElementSibling)p.insertBefore(row.nextElementSibling,row);updatePreview()}
function showConfirm(html){let root=$('#modalRoot')||document.body;root.innerHTML=`<div class="modal-backdrop"><section class="modal-card">${html}</section></div>`}
function resetAffection(){let state=readState(),cid=state.active,name=state.characters?.find(c=>c.id===cid)?.name||'Character',heart=clamp(state.affection?.[cid]?.value);showConfirm(`<p class="label">RESET AFFECTION</p><h2>Reset ${esc(name)}'s affection?</h2><p>Heart ${heart} → 0</p><p class="muted">Memories, Events and History will not be deleted.</p><div class="button-row"><button class="gold-button danger" data-confirm-reset-affection>RESET</button><button class="ghost-button" data-rel-modal-close>CANCEL</button></div>`)}
function doResetAffection(){let state=readState(),cid=state.active;if(!cid)return;state.affection=state.affection||{};state.affection[cid]={...(state.affection[cid]||{}),value:0};writeState(state);let saved=readState();if(Number(saved.affection?.[cid]?.value)!==0){toast('RESET FAILED');return}if($('#rAffV44'))$('#rAffV44').value='0';updatePreview();emitStorage();closeModal();toast('AFFECTION RESET')}
function restoreDefaultStages(){showConfirm(`<p class="label">RESTORE DEFAULT STAGES</p><h2>Restore default stages?</h2><p>현재 작성한 Relationship Stage 설정이 기본 11단계 설정으로 교체됩니다.</p><div class="button-row"><button class="gold-button" data-confirm-restore-stages>RESTORE</button><button class="ghost-button" data-rel-modal-close>CANCEL</button></div>`)}
function doRestoreStages(){let state=readState(),cid=state.active;if(!cid)return;state.affection=state.affection||{};let old=state.affection[cid]||{};if(!Object.prototype.hasOwnProperty.call(old,'legacyStages')&&old.stages)old.legacyStages=JSON.parse(JSON.stringify(old.stages));state.affection[cid]={...old,stageTable:DEFAULT_STAGES.map(r=>({...r})),stages:serializeStages(DEFAULT_STAGES)};writeState(state);let table=$('[data-stage-table]');if(table)table.innerHTML=DEFAULT_STAGES.map(stageRow).join('');updatePreview();emitStorage();closeModal();toast('DEFAULT STAGES RESTORED')}
function closeModal(){let root=$('#modalRoot');if(root)root.innerHTML=''}
function handleClick(e){let t=e.target;if(!(t instanceof Element))return;if(t.closest('[data-save-rel-v44]')){e.preventDefault();e.stopImmediatePropagation();saveRelationship();return}if(t.closest('[data-reset-affection]')){e.preventDefault();resetAffection();return}if(t.closest('[data-confirm-reset-affection]')){e.preventDefault();doResetAffection();return}if(t.closest('[data-restore-default-stages]')){e.preventDefault();restoreDefaultStages();return}if(t.closest('[data-confirm-restore-stages]')){e.preventDefault();doRestoreStages();return}if(t.closest('[data-rel-modal-close]')){e.preventDefault();closeModal();return}if(t.closest('[data-stage-add]')){e.preventDefault();let gap=suggestedGap();if(!gap){toast('NO EMPTY HEART RANGE');return}let table=$('[data-stage-table]');if(table)table.insertAdjacentHTML('beforeend',stageRow({min:gap.min,max:gap.max,name:'NEW STAGE',description:''}));updatePreview();return}let del=t.closest('[data-stage-delete]');if(del){del.closest('[data-stage-row]')?.remove();updatePreview();return}let up=t.closest('[data-stage-up]');if(up){moveStage(up.closest('[data-stage-row]'),-1);return}let down=t.closest('[data-stage-down]');if(down){moveStage(down.closest('[data-stage-row]'),1);return}if(t.closest('[data-add-char]'))setTimeout(()=>{ensureDefaultStages();patchRelationship()},0)}
function handleInput(e){let t=e.target;if(!(t instanceof Element))return;if(t.matches('[data-stage-min],[data-stage-max],[data-stage-name],[data-stage-description],#rAffV44'))updatePreview();if(t.closest('[data-relationship-v44]'))e.stopImmediatePropagation()}
function handleChange(e){let t=e.target;if(!(t instanceof Element))return;if(t.id==='rMoodV44'){let mood=String(t.value),note=$('[data-mood-note]');if(note)note.innerHTML=`<strong>${esc(mood)} — ${esc(moodLabel(mood))}</strong>`}if(t.closest('[data-relationship-v44]'))e.stopImmediatePropagation()}
function observe(){let app=$('#app');if(app)new MutationObserver(()=>queueMicrotask(patchRelationship)).observe(app,{childList:true,subtree:true})}
document.addEventListener('click',handleClick,true);document.addEventListener('input',handleInput,true);document.addEventListener('change',handleChange,true);document.addEventListener('DOMContentLoaded',()=>{ensureDefaultStages();observe();patchRelationship()});window.addEventListener('load',()=>{ensureDefaultStages();patchRelationship()});setTimeout(()=>{ensureDefaultStages();patchRelationship()},120);
})();