(()=>{
'use strict';
if(window.__HELLAVERSE_SETTINGS_RESCUE_V3__)return;
window.__HELLAVERSE_SETTINGS_RESCUE_V3__=1;
const K='hellaverse_dialogue_state_v1';
const ORIGINS={HELLBORN:'HELL',SINNER:'HELL',ANGEL:'HEAVEN',WINNER:'HEAVEN'};
let queued=false;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const read=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')||{}}catch{return{}}};
const write=s=>{try{localStorage.setItem(K,JSON.stringify(s));window.dispatchEvent(new CustomEvent('hellaverse:state-updated',{detail:{source:'settings-rescue',clearDirty:false}}));return true}catch{return false}};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
function style(){if($('#hvSettingsRescueStyle'))return;const st=document.createElement('style');st.id='hvSettingsRescueStyle';st.textContent=`
.hv-settings-rescue{border:0!important;background:transparent!important;color:var(--muted)!important;padding:8px 0!important;letter-spacing:.14em!important;font-size:.75rem!important;text-transform:uppercase!important}.hv-settings-rescue:hover{color:var(--gold)!important}
.hv-settings-fallback{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.hv-settings-fallback .settings-panel{display:grid;gap:12px}.hv-settings-fallback .full{grid-column:1/-1}.hv-sr-origins{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hv-sr-origins button{border:1px solid var(--line);background:transparent;color:var(--text);padding:10px;text-align:left}.hv-sr-origins button.on{border-color:var(--gold);color:var(--gold)}.hv-sr-row{display:flex;gap:10px;flex-wrap:wrap}.hv-sr-row button{flex:1}.hv-sr-msg{min-height:20px;color:var(--gold);font-size:.78rem}@media(max-width:760px){.hv-settings-fallback{grid-template-columns:1fr}.hv-settings-fallback .full{grid-column:auto}}
`;document.head.appendChild(st)}
function normalizeButton(button){button.classList.add('hv-settings-rescue');button.dataset.page='settings';button.dataset.hvSettingsRescue='1';button.textContent='⚙ SETTINGS'}
function ensureOne(root){if(!root)return;let list=$$('[data-page="settings"],[data-hv-settings-rescue]',root),keep=list[0];if(!keep){keep=document.createElement('button');keep.className='nav-button';normalizeButton(keep);root.appendChild(keep)}else normalizeButton(keep);list.slice(1).forEach(x=>x.remove())}
function ensureButtons(){style();ensureOne($('.game-hud .main-nav'));$$('.room-hud [data-hv-settings-rescue]').forEach(x=>x.remove())}
function coreSettingsPresent(){return !!$('.site-shell.page-settings .settings-grid')}
function fallbackHtml(){const s=read(),o=String(s.player?.origin||'').toUpperCase(),set=s.settings||{};return `<div class="settings-grid hv-settings-fallback" id="hvSettingsFallback">
<section class="settings-panel"><p class="label">PLAYER</p><h2>PLAYER PROFILE</h2><label>Name<input id="hvSrName" maxlength="30" value="${esc(s.player?.name||'')}"></label><div class="hv-sr-origins" id="hvSrOrigins" data-origin="${esc(o)}">${Object.keys(ORIGINS).map(k=>`<button type="button" class="${o===k?'on':''}" data-hv-sr-origin="${k}"><strong>${k}</strong><br><small>${ORIGINS[k]}</small></button>`).join('')}</div><p>ROLE · EXTRA / LOW PROFILE</p><button class="gold-button" data-hv-sr-save-player>SAVE PLAYER</button><p class="hv-sr-msg" id="hvSrPlayerMsg"></p></section>
<section class="settings-panel"><p class="label">APPEARANCE</p><label>Gold<input id="hvSrGold" type="color" value="${esc(set.gold||'#C9A66B')}"></label><label>Wine<input id="hvSrWine" type="color" value="${esc(set.wine||'#A72D48')}"></label><label>Font Size<input id="hvSrSize" type="range" min="14" max="20" value="${Number(set.size||16)}"></label><label>Locked Choices<select id="hvSrLocked"><option value="disabled" ${set.lockedChoices==='disabled'?'selected':''}>disabled</option><option value="questionMarks" ${set.lockedChoices==='questionMarks'?'selected':''}>???</option><option value="hidden" ${set.lockedChoices==='hidden'?'selected':''}>hidden</option></select></label><button class="gold-button" data-hv-sr-save-look>SAVE APPEARANCE</button></section>
<section class="settings-panel"><p class="label">DATA BACKUP</p><button class="gold-button" data-hv-sr-export>BACKUP EXPORT</button><label class="import-label">RESTORE IMPORT<input id="hvSrImport" type="file" accept="application/json"></label></section>
<section class="settings-panel danger-zone full"><p class="label">DANGER ZONE</p><div class="hv-sr-row"><button class="ghost-button danger" data-hv-sr-danger="history">DELETE CONVERSATIONS</button><button class="ghost-button danger" data-hv-sr-danger="memories">DELETE MEMORIES</button><button class="ghost-button danger" data-hv-sr-danger="content">DELETE CONTENT</button><button class="ghost-button danger" data-hv-sr-danger="all">RESET GAME STATE</button></div></section></div>`}
function ensureSettingsPage(){const s=read(),shell=$('.site-shell');if(s.page!=='settings'||!shell?.classList.contains('page-settings'))return;if(coreSettingsPresent())return;const page=$('.page.active')||$('.page');if(page)page.innerHTML=fallbackHtml()}
function openSettingsFallback(){const s=read();s.page='settings';write(s);setTimeout(()=>{ensureButtons();ensureSettingsPage()},80)}
function savePlayer(){const root=$('#hvSettingsFallback'),name=$('#hvSrName',root)?.value.trim()||'',origin=$('#hvSrOrigins',root)?.dataset.origin||'';if(!name||!ORIGINS[origin]){const m=$('#hvSrPlayerMsg',root);if(m)m.textContent='이름과 출신을 모두 정해줘.';return}const s=read();s.player={...(s.player||{}),name,origin,realm:ORIGINS[origin],role:'EXTRA',profileSetup:true};s.flags=s.flags&&typeof s.flags==='object'?s.flags:{};Object.keys(s.flags).forEach(k=>{if(k.startsWith('player.origin.')||k.startsWith('player.realm.'))delete s.flags[k]});s.flags['player.origin.'+origin.toLowerCase()]=true;s.flags['player.realm.'+ORIGINS[origin].toLowerCase()]=true;s.flags['player.role.extra']=true;write(s);const m=$('#hvSrPlayerMsg',root);if(m)m.textContent='PLAYER SAVED'}
function saveLook(){const s=read();s.settings=s.settings||{};s.settings.gold=$('#hvSrGold')?.value||'#C9A66B';s.settings.wine=$('#hvSrWine')?.value||'#A72D48';s.settings.size=Number($('#hvSrSize')?.value||16);s.settings.lockedChoices=$('#hvSrLocked')?.value||'disabled';write(s);document.documentElement.style.setProperty('--gold',s.settings.gold);document.documentElement.style.setProperty('--wine',s.settings.wine);document.documentElement.style.setProperty('--body-size',s.settings.size+'px')}
function exportData(){const s=read(),b=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='hellaverse-dialogue-backup.json';a.click();URL.revokeObjectURL(u)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const s=JSON.parse(r.result);localStorage.setItem(K,JSON.stringify(s));window.location.reload()}catch{alert('백업 파일을 읽지 못했습니다.')}};r.readAsText(file)}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;ensureButtons();ensureSettingsPage()})}
document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;if(t.closest('[data-hv-settings-rescue]')){setTimeout(()=>{if(!coreSettingsPresent())openSettingsFallback()},40);return}const o=t.closest('[data-hv-sr-origin]')?.dataset.hvSrOrigin;if(o&&ORIGINS[o]){const root=$('#hvSrOrigins');if(!root)return;root.dataset.origin=o;$$('[data-hv-sr-origin]',root).forEach(b=>b.classList.toggle('on',b.dataset.hvSrOrigin===o));return}if(t.closest('[data-hv-sr-save-player]'))return savePlayer();if(t.closest('[data-hv-sr-save-look]'))return saveLook();if(t.closest('[data-hv-sr-export]'))return exportData();const d=t.closest('[data-hv-sr-danger]')?.dataset.hvSrDanger;if(d&&confirm('정말 실행할까요?')){let s=read();if(d==='history')s.conversationHistory=[];if(d==='memories')s.memories=[];if(d==='content'){s.dialogues=[];s.gifts=[];s.collectionItems=[];s.ownedItems=[];s.newCollectionItems=[];s.rewards=[];s.thoughts=[]}if(d==='all'){localStorage.removeItem(K);location.reload();return}write(s);ensureSettingsPage()}},true);
document.addEventListener('change',e=>{if(e.target?.id==='hvSrImport')importData(e.target.files?.[0])});
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('hellaverse:state-updated',schedule);document.addEventListener('DOMContentLoaded',schedule);window.addEventListener('load',schedule);if(document.readyState!=='loading')schedule();
})();
