(()=>{
'use strict';
if(window.__HELLAVERSE_LUCIFER_ACTION_FILE_V1__)return;window.__HELLAVERSE_LUCIFER_ACTION_FILE_V1__=1;
const K='hellaverse_dialogue_state_v1',VK='hellaverse_lucifer_action_file_v1',CID='lucifer-morningstar';let v=0;try{v=Number(localStorage.getItem(VK)||0)}catch{}if(v>=1)return;
const read=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')||{}}catch{return{}}};
const ch=(id,text,response,delta=0,opt={})=>({id,type:'action',text,playerLine:opt.playerLine||text,response,affectionDelta:delta,requiredAffection:Number(opt.requiredAffection||0),requiredStage:opt.requiredStage||'',requiredMood:'ANY',requiredFlags:opt.requiredFlags||'',blockedFlags:'',requiredMemoryTags:'',lockDisplay:'disabled',setFlags:opt.setFlags||'',removeFlags:'',addMemoryTitle:'',addMemorySummary:'',addMemoryTags:'',moodChange:opt.moodChange||'',unlockItemId:'',nextNodeId:'',endConversation:true});
const scene=(id,title,opening,reaction,choices,min=0)=>({id,characterId:CID,title,kind:'TALK',repeatable:true,requiredAffection:min,maxAffection:100,requiredStage:'',requiredMood:'ANY',requiredFlags:'',blockedFlags:'',requiredMemoryTags:'',blockedMemoryTags:'',requiredItemIds:'',priority:11,probability:100,opening,exitLine:'',after:'',used:false,nodes:[{id:'start',speaker:'character',text:reaction,choices}],openingNodeId:'start'});
const rows=[
scene('lucifer-file-act-01','떨어진 오리 줍기','작업대 아래로 작은 고무 오리가 굴러 떨어진다.','루시퍼는 허리를 숙이려다 당신 쪽을 힐끗 본다.',[ch('lucifer-file-act-01-c1','오리를 주워 건넨다.','“오, 고마워. 얘가 탈출 계획을 세운 모양이야.”',1),ch('lucifer-file-act-01-c2','발끝으로 루시퍼 쪽에 밀어준다.','“정교하진 않지만 효율적이군.”',0),ch('lucifer-file-act-01-c3','못 본 척한다.','루시퍼가 결국 직접 주워 들며 중얼거린다. “충성심이라고는 없군, 둘 다.”',0)]),
scene('lucifer-file-act-02','서류 정리 돕기','책상 가장자리의 서류 더미가 금방이라도 무너질 듯 흔들린다.','“건드리면 무너지고, 안 건드려도 무너질 거야. 완벽한 행정 상태지.”',[ch('lucifer-file-act-02-c1','서류를 종류별로 나눈다.','루시퍼가 눈을 크게 뜬다. “세상에. 실제 해결책을 들고 왔네.”',2,{setFlags:'lucifer.player_helped_with_work'}),ch('lucifer-file-act-02-c2','맨 위 서류만 조심히 옮긴다.','“좋아. 아주 작고 현실적인 진전이야.”',1),ch('lucifer-file-act-02-c3','서류 더미를 살짝 눌러 평평하게 만든다.','“그건 정리가 아니라 압축이잖아. …근데 조금 마음에 드네.”',1)]),
scene('lucifer-file-act-03','피아노 옆에 앉기','루시퍼가 피아노 앞에서 짧은 멜로디를 반복하고 있다.','그는 당신이 들어온 걸 알지만 연주를 멈추지 않는다.',[ch('lucifer-file-act-03-c1','말없이 옆에 앉는다.','몇 마디가 더 흐른 뒤 그가 작게 웃는다. “조용히 있어주는 것도 재능이네.”',2,{setFlags:'lucifer.music_shared'}),ch('lucifer-file-act-03-c2','박자에 맞춰 손가락을 두드린다.','루시퍼가 곡 사이에 당신 리듬을 슬쩍 섞어 넣는다. “나쁘지 않은데?”',2),ch('lucifer-file-act-03-c3','건반 하나를 장난스럽게 누른다.','불협화음이 울린다. 루시퍼가 당신을 본다. “…용감하군.”',1)]),
scene('lucifer-file-act-04','사과 타르트 나누기','접시에는 사과 타르트 한 조각만 남아 있다.','“우리가 문명인이라면 반으로 나누겠지. 내가 왕이라는 사실은 잠깐 잊고.”',[ch('lucifer-file-act-04-c1','정확히 반으로 자른다.','“완벽해. 정치보다 공정한 분배가 여기 있었군.”',2,{setFlags:'lucifer.apple_tart_shared'}),ch('lucifer-file-act-04-c2','큰 쪽을 루시퍼에게 준다.','그가 잠깐 당신을 보다가 웃는다. “이런 식으로 왕실의 환심을 사는 거야?”',2),ch('lucifer-file-act-04-c3','작은 쪽을 루시퍼에게 준다.','“아. 혁명의 시작이군. 기억해두겠어.”',0)]),
scene('lucifer-file-act-05','날개에 붙은 깃털','루시퍼의 어깨 뒤에 작은 흰 깃털 하나가 느슨하게 걸려 있다.','그는 아직 눈치채지 못한 듯하다.',[ch('lucifer-file-act-05-c1','말로 알려준다.','루시퍼가 손을 뒤로 뻗다가 헛손질한다. “어디? 왼쪽? 내 왼쪽?”',1),ch('lucifer-file-act-05-c2','허락을 구하고 떼어준다.','잠깐 굳었던 어깨가 이내 풀린다. “응. 고마워.”',2,{requiredAffection:30,setFlags:'lucifer.wings_topic_shared'}),ch('lucifer-file-act-05-c3','그냥 둔다.','몇 분 뒤 루시퍼가 깃털을 발견하고 당신을 의심스럽게 본다. “알고 있었지?”',0)],20),
scene('lucifer-file-act-06','방 장식 바로잡기','벽의 작은 액자가 아주 미세하게 기울어져 있다.','루시퍼는 다른 일을 하고 있지만 시선이 자꾸 액자 쪽으로 간다.',[ch('lucifer-file-act-06-c1','액자를 똑바로 맞춘다.','그가 즉시 고개를 든다. “고마워. 이제야 세상이 정상으로 돌아왔군.”',2),ch('lucifer-file-act-06-c2','일부러 반대쪽으로 더 기울인다.','루시퍼가 천천히 당신을 본다. “전쟁을 원해?”',-1),ch('lucifer-file-act-06-c3','옆 액자까지 같이 정리한다.','“오. 위험할 정도로 유능하네. 계속해봐.”',2)]),
scene('lucifer-file-act-07','찰리의 사진 돌려놓기','책상 위 가족사진이 다른 서류에 반쯤 가려져 있다.','루시퍼는 서류를 찾느라 아직 사진을 보지 못했다.',[ch('lucifer-file-act-07-c1','사진이 보이게 앞쪽으로 옮긴다.','루시퍼의 손이 잠깐 멈춘다. “…응. 거기가 더 낫네.”',2,{setFlags:'lucifer.family_memory_shared'}),ch('lucifer-file-act-07-c2','사진은 건드리지 않는다.','루시퍼가 곧 사진을 발견해 서류를 치운다. 표정이 잠깐 부드러워진다.',1),ch('lucifer-file-act-07-c3','사진을 들어 자세히 본다.','루시퍼가 자연스럽게 손을 내민다. “그건 여기 둘게.” 목소리는 부드럽지만 선은 분명하다.',0)]),
scene('lucifer-file-act-08','천국 우편 봉투','책상 한쪽에 낯선 흰 봉투가 놓여 있다. 금빛 봉인은 아직 뜯기지 않았다.','루시퍼는 봉투를 보고도 손을 대지 않는다.',[ch('lucifer-file-act-08-c1','봉투에서 손을 뗀다.','루시퍼가 아주 작게 숨을 내쉰다. “고마워.”',2,{requiredAffection:35}),ch('lucifer-file-act-08-c2','루시퍼 쪽으로 밀어준다.','그가 봉투를 보다가 손가락으로 다시 밀어놓는다. “조금 있다가.”',1,{requiredAffection:35}),ch('lucifer-file-act-08-c3','발신인을 확인하려 한다.','루시퍼의 손이 먼저 봉투를 덮는다. “그건 내가 볼게.” 농담 없는 목소리다.',-1,{moodChange:'ANNOYED'})],30)
];
const s=read();s.dialogues=Array.isArray(s.dialogues)?s.dialogues:[];s.dialogueFileMap=s.dialogueFileMap&&typeof s.dialogueFileMap==='object'?s.dialogueFileMap:{};for(const x of rows){const i=s.dialogues.findIndex(y=>y?.id===x.id);i>=0?s.dialogues[i]=x:s.dialogues.push(x);s.dialogueFileMap[x.id]='ACTION'}localStorage.setItem(K,JSON.stringify(s));localStorage.setItem(VK,'1');
})();